"""Canonical apps_rg full-run output filenames."""

from __future__ import annotations

APPS_RG_MANDATORY_RUN_OUTPUT_JSON = "APPS_RG_MANDATORY_RUN_OUTPUT.json"
APPS_RG_MANDATORY_RUN_OUTPUT_MD = "02_section_lane_summary_table.md"
BCG_EXECUTIVE_OUTPUT_MD = "01_BCG_executive_output.md"
OUTPUT_BISECT_MD = "02_output_bisect.md"
L7_AUDIT_ABILITY_OUTPUT_MD = "03_L7_audit_ability_output.md"
LEGACY_APPS_RG_MANDATORY_RUN_OUTPUT_MD = "APPS_RG_MANDATORY_RUN_OUTPUT.md"
LEGACY_BCG_EXECUTIVE_OUTPUT_MD = "BCG_EXECUTIVE_OUTPUT.md"
FULL_RUN_SECTION_STATUS_MD = "FULL_RUN_SECTION_STATUS.md"
FULL_RUN_SECTION_STATUS_JSON = "full_run_section_status.json"
APPS_RG_SECTION_LOCKDOWN_MD = "APPS_RG_SECTION_LOCKDOWN.md"
APPS_RG_SECTION_LOCKDOWN_JSON = "APPS_RG_SECTION_LOCKDOWN.json"
REVIEW_BUNDLE_FILENAME = "review_bundle.zip"
REVIEW_INDEX_FILENAME = "REVIEW_INDEX.md"
FINAL_RESUME_OUTPUT_TXT = "FINAL_RESUME_OUTPUT.txt"
FINAL_RESUME_OUTPUT_JSON = "FINAL_RESUME_OUTPUT.json"
FINAL_RESUME_DOCX_RELPATH = "outputs/resume.docx"
FINAL_RESUME_ASSEMBLY_JSON_RELPATH = "modular_r4/final_resume_assembly/final_resume.json"

MANDATORY_OUTPUT_FILENAMES: tuple[str, ...] = (
    BCG_EXECUTIVE_OUTPUT_MD,
    OUTPUT_BISECT_MD,
    APPS_RG_MANDATORY_RUN_OUTPUT_MD,
    APPS_RG_MANDATORY_RUN_OUTPUT_JSON,
    L7_AUDIT_ABILITY_OUTPUT_MD,
    FINAL_RESUME_OUTPUT_TXT,
    FINAL_RESUME_OUTPUT_JSON,
    APPS_RG_SECTION_LOCKDOWN_MD,
    APPS_RG_SECTION_LOCKDOWN_JSON,
    FULL_RUN_SECTION_STATUS_MD,
    FULL_RUN_SECTION_STATUS_JSON,
    REVIEW_INDEX_FILENAME,
    REVIEW_BUNDLE_FILENAME,
)

__all__ = [
    "APPS_RG_MANDATORY_RUN_OUTPUT_JSON",
    "APPS_RG_MANDATORY_RUN_OUTPUT_MD",
    "APPS_RG_SECTION_LOCKDOWN_JSON",
    "APPS_RG_SECTION_LOCKDOWN_MD",
    "BCG_EXECUTIVE_OUTPUT_MD",
    "FINAL_RESUME_ASSEMBLY_JSON_RELPATH",
    "FINAL_RESUME_DOCX_RELPATH",
    "FINAL_RESUME_OUTPUT_JSON",
    "FINAL_RESUME_OUTPUT_TXT",
    "FULL_RUN_SECTION_STATUS_JSON",
    "FULL_RUN_SECTION_STATUS_MD",
    "L7_AUDIT_ABILITY_OUTPUT_MD",
    "LEGACY_APPS_RG_MANDATORY_RUN_OUTPUT_MD",
    "LEGACY_BCG_EXECUTIVE_OUTPUT_MD",
    "MANDATORY_OUTPUT_FILENAMES",
    "OUTPUT_BISECT_MD",
    "REVIEW_BUNDLE_FILENAME",
    "REVIEW_INDEX_FILENAME",
]
